framework_generate_cmd:
    args: ""
    type: kitex
idl_repos:
    - repo_name: repo_name1
      git_url: git@github.com:ViolaPioggia/IDL_REPO.git
      branch: main
      commit: fd534d04f6a868fa9e727161ec0625fb71ecc7bc
idls:
    - idl_path: ./echo.thrift
      repo_name: repo_name1
      service_name: service_one
    - idl_path: ./hello.thrift
      repo_name: repo_name1
      service_name: service_two
